GET http://localhost:5239/tasks
###
GET http://localhost:5239/tasks/4
###
GET http://localhost:5239/tasks/99
###
POST http://localhost:5239/tasks 
Content-Type: application/json

{
    "title": "",
    "TaskDatum": "2025-12-29"
}
###
PUT http://localhost:5239/tasks/6
Content-Type: application/json

{
    "id": 6,
    "title": "Spielen und Einkaufen",
    "isComplete": false,
    "taskDatum": "2025-12-28"
}

###
DELETE http://localhost:5239/tasks/3
